"""Example: a tiny LLM agent.

The same shape as ``echo_agent.py``, except the reply is generated by an LLM
instead of being a fixed prefix. The point is to show that linc gives you a
clean ``unread -> reply`` loop — the LLM call is just one function the agent
slots in.

We keep the LLM call abstract here so the example runs without any extra deps:
replace ``call_llm`` with whatever client you prefer (OpenAI, Anthropic, local
Ollama, ...).

Per-conversation context: this example keeps a tiny in-memory ``history`` dict
keyed by ``conv_id``. For real systems, fetch durable history from linc itself
via ``slack.conv(conv_id).history(limit=20)`` so a restart of the agent does
not lose context.
"""

from __future__ import annotations

import asyncio
import logging
from collections import defaultdict, deque

from linc import Linc

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("llm_agent")

SYSTEM_PROMPT = "You are a concise, friendly assistant. Reply in one or two sentences."


async def call_llm(system: str, conversation: list[tuple[str, str]]) -> str:
    """Stub LLM call — replace with a real client.

    ``conversation`` is a list of (role, text) tuples in chronological order.
    Roles are "user" or "assistant".
    """
    # Trivial baseline: echo the last user message back. Replace this body.
    last_user = next((t for r, t in reversed(conversation) if r == "user"), "")
    return f"(stub LLM) you said: {last_user}"


async def main() -> None:
    history: dict[str, deque[tuple[str, str]]] = defaultdict(lambda: deque(maxlen=20))

    async with Linc(".linc") as linc:
        slack = linc.slack()
        log.info("llm agent started; ctrl-c to stop")
        while True:
            unread = await slack.read_unread()
            for m in unread:
                history[m.conv_id].append(("user", m.content.text or ""))
                reply = await call_llm(SYSTEM_PROMPT, list(history[m.conv_id]))
                history[m.conv_id].append(("assistant", reply))
                log.info("[%s] -> %s", m.conv_id, reply)
                await slack.send(reply, conv_id=m.conv_id)
            await asyncio.sleep(1.0)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
